services:
  mysql:
    image: mysql:8.0.39
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ../db
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
volumes:
  mysql_data: